#!/bin/bash

export DOSBOX_DRIVEC=${DOSBOX_DRIVEC:-/dados/Jogos/DOSBox}

confdir="$DOSBOX_DRIVEC"/conf
defaultconf="$confdir"/default.linux.conf
gameconf="$confdir"/"$1".conf

args=(-conf "$defaultconf")

if [[ -f "$gameconf" ]]; then
	args+=(-conf "$gameconf")
	shift
fi

/usr/bin/dosbox "${args[@]}" "$@"
