#!/bin/bash

mydir=$(dirname "$(readlink -f "$0")")

fatal()   { [[ "${1:-}" ]] && echo "$myname: error: $@" >&2 ; exit 1; }

if ! [[ -d "$DOSBOX_DRIVEC" ]]; then
	fatal "DOSBOX_DRIVEC is not set or does not exist, run the installer! [$DOSBOX_DRIVEC]"
fi

DOSBOX_CONFDIR=${DOSBOX_CONFDIR:-"$mydir"/conf}

defaultconf="$DOSBOX_CONFDIR"/default.linux.conf
gameconf=""

args=(-conf "$defaultconf")

while (( $# )); do
	case "$1" in
	-h|--help) man dosbox; exit ;;
	-*       ) args+=( "$1" )   ;;
	*        )
		if [[ "$gameconf" ]]; then
			args+=( "$1" )
		else
			gameconf="$DOSBOX_CONFDIR"/"$1".conf
			if [[ -f "$gameconf" ]]; then
				args+=(-conf "$gameconf")
			else
				args+=( "$1" )
				gameconf=""
			fi
		fi
	;;
	esac
	shift
done

cd "$DOSBOX_DRIVEC"  # default.linux.conf has 'mount c .'

set -x
/usr/bin/dosbox "${args[@]}" "$@"
